### ISSUE TITLE
Ident string garbled

### ISSUE THREAD

**Issue by aboroska** [garazdawi/syslogger#5]
Somehow the "ident" string gets corrupted on Linux. Tested on Ubuntu bionic and focal. With Erlang 24.1.6 and 23.3.4.9. On both arm64 and amd64.

Maybe related to `rsyslogd` although both a recent and and older version fails:

```
rsyslogd -v
rsyslogd  8.2001.0 (aka 2020.01) compiled with:
	PLATFORM:				aarch64-unknown-linux-gnu
```

```
rsyslogd -v
rsyslogd 8.32.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
```

The rsyslog template is the default one:
```
grep Template /etc/rsyslog.conf
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
```

To reproduce run `rebar3 ct`.

`{test_case_failed,"Could not find \"testytest\" in /var/log/syslog"}`

```
Nov 19 22:01:01 ip-172-31-8-19 rebar3: 2021-11-19T22:01:01.507192+00:00 error: test log message
Nov 19 22:01:02 ip-172-31-8-19 rebar3: 2021-11-19T22:01:02.009385+00:00 alert: test log message
Nov 19 22:01:02 ip-172-31-8-19 rebar3: 2021-11-19T22:01:02.511026+00:00 error: test log message
Nov 19 22:01:02 ip-172-31-8-19 rebar3: 2021-11-19T22:01:02.511026+00:00 error: test log message
Nov 19 22:01:03 ip-172-31-8-19 <E0>^MnD<FF><FF>[98668]: 8]: 2021-11-19T22:01:03.049256+00:00 error: testy log message
```

To debug it might be helpful to set in `/etc/rsyslog.conf`:
```
$ActionFileDefaultTemplate RSYSLOG_DebugFormat
```

**Comment by garazdawi** [comment]
I'm not really using or maintaining this code anymore. I think that @NelsonVides fork may be a bit more up-to-date.

**Comment by NelsonVides** [comment]
@aboroska fixed in the latest master 🙂
